select * from Equipment;
select * from StudentsGroup;
select * from Room;
select * from lecturers;
select * from Participants;
select * from Courses;
select * from belongs;
select * from teaches_the;
select * from uses;
